# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/kcontacts' : '@latest'
    'kde/pim/akonadi' : '@same'
    'kde/pim/akonadi-contacts' : '@same'
    'kde/pim/akonadi-mime' : '@same'
    'kde/pim/akonadi-search' : '@same'
    'kde/pim/grantleetheme' : '@same'
    'kde/pim/kidentitymanagement' : '@same'
    'kde/pim/kldap' : '@same'
    'kde/pim/kmailtransport' : '@same'
    'kde/pim/kmbox' : '@same'
    'kde/pim/kmime' : '@same'
    'kde/pim/kpimtextedit' : '@same'
    'kde/pim/libgravatar' : '@same'
    'kde/pim/libkdepim' : '@same'
    'kde/pim/libkleo' : '@same'
    'kde/pim/pimcommon' : '@same'
    'third-party/grantlee' : '@stable'
    'kdesupport/qca' : '@latest'
