# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcontacts' : '@latest'
    'pim/akonadi' : '@same'
    'pim/akonadi-contacts' : '@same'
    'pim/akonadi-mime' : '@same'
    'pim/akonadi-search' : '@same'
    'pim/grantleetheme' : '@same'
    'pim/kidentitymanagement' : '@same'
    'pim/kmailtransport' : '@same'
    'pim/kmbox' : '@same'
    'pim/kmime' : '@same'
    'pim/kpimtextedit' : '@same'
    'pim/libgravatar' : '@same'
    'pim/libkdepim' : '@same'
    'pim/libkleo' : '@same'
    'pim/pimcommon' : '@same'
    'third-party/grantlee' : '@stable'
    'kdesupport/qca' : '@latest'
Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD']
